### ISSUE TITLE
Poly play of mono Synth

### ISSUE THREAD

**Issue by Hudaldadi** [pichenettes/midipal#3]
I bought the MIDI Pal long time ago for one purpose:

to play 6 Mono-Synth as one Poly by splitting the notes to 6 individual MIDI channels.

But I can't see this feature in the new Firmware version anymore.

Or is it in the "Note dispatcher / voice stealing / polyphonic driver"

**Comment by pichenettes** [comment]
This feature has always been called "note dispatcher".

Please note that this site is for reporting issues in the codebase. For support, please use the forum or the contact form on the Mutable Instruments website.

**Comment by Hudaldadi** [comment]
Thank so much, answering anyway.
Found the official Forum:  https://forum.mutable-instruments.net/c/legacy/midipal/
And I am pretty excited about the editor, makes it again to such genius project.
All the best.
